version: "3.8"

services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    hostname: db

  app:
      container_name: "app"
      build: 
        context: app
      restart: always
      tty: true
      volumes:
        - ./app:/app
      ports:
        - 8888:8888
        - 5678:5678
      expose:
        - "5678"
